version: '3.7'

services:
  web:
    image: killka1997/autodom-img
   

    expose:
    - 8000
    volumes:
      - static_volume:/Autodom-app/Autodom/static/:rw
      - media_volume:/Autodom-app/Autodom/media/:rw
    environment:
      - DJANGO_SETTINGS_MODULE=Autodom.settings
      - BROKER_URL=redis://redis:6379
      - RESULT_BACKEND=redis://redis:6379
      - POSTGRES_PASSWORD=qwerty1234
      - POSTGRES_USER=admin123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - LETSENCRYPT_HOST=localhost
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8000
      - ALLOWED_HOST=jelastic.minassyants.kz
      - EMAIL_HOST=smtp.mail.ru
      - EMAIL_PORT=465
      - EMAIL_HOST_USER=info@minassyants.kz
      - EMAIL_HOST_PASSWORD=SyIatpOYi~33
    depends_on:
      - redis
      - db

  celery:
    image: killka1997/autodom-img
   
    command: celery -A Autodom worker --autoscale=5,1 --loglevel=info
    volumes:
      - static_volume:/Autodom-app/Autodom/static/:rw
    environment:
      - DJANGO_SETTINGS_MODULE=Autodom.settings
      - BROKER_URL=redis://redis:6379
      - RESULT_BACKEND=redis://redis:6379
      - POSTGRES_PASSWORD=qwerty1234
      - POSTGRES_USER=admin123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - ALLOWED_HOST=jelastic.minassyants.kz
      - EMAIL_HOST=smtp.mail.ru
      - EMAIL_PORT=465
      - EMAIL_HOST_USER=info@minassyants.kz
      - EMAIL_HOST_PASSWORD=SyIatpOYi~33
    depends_on:
      - web
      - redis
  
  beat:
    image: killka1997/autodom-img
   
    command: celery -A Autodom beat -l DEBUG
    volumes:
      - static_volume:/Autodom-app/Autodom/static/:rw
    environment:
      - DJANGO_SETTINGS_MODULE=Autodom.settings
      - BROKER_URL=redis://redis:6379
      - RESULT_BACKEND=redis://redis:6379
      - POSTGRES_PASSWORD=qwerty1234
      - POSTGRES_USER=admin123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - ALLOWED_HOST=jelastic.minassyants.kz
      - EMAIL_HOST=smtp.mail.ru
      - EMAIL_PORT=465
      - EMAIL_HOST_USER=info@minassyants.kz
      - EMAIL_HOST_PASSWORD=SyIatpOYi~33
    depends_on:
      - web
      - redis
      - celery
      - db


  redis:
    image: redis


  flower:
    image: killka1997/autodom-img
   
    command: celery -A Autodom flower --address=0.0.0.0 --port=5566
    expose:
     - 5566
    environment:
      - DJANGO_SETTINGS_MODULE=Autodom.settings
      - BROKER_URL=redis://redis:6379
      - RESULT_BACKEND=redis://redis:6379
      - POSTGRES_PASSWORD=qwerty1234
      - POSTGRES_USER=admin123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - ALLOWED_HOST=jelastic.minassyants.kz
      - EMAIL_HOST=smtp.mail.ru
      - EMAIL_PORT=465
      - EMAIL_HOST_USER=info@minassyants.kz
      - EMAIL_HOST_PASSWORD=SyIatpOYi~33
    depends_on:
      - celery
      - redis

  db:
      image: postgres
    
      expose:
        - 5432
      volumes:
      - postgres_data:/var/lib/postgresql/data/
      environment:
      - POSTGRES_PASSWORD=qwerty1234
      - POSTGRES_USER=admin123
      - POSTGRES_HOST=db

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/vhost.d
      - /etc/nginx/certs
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/default_location:/etc/nginx/vhost.d/default_location
      - static_volume:/home/app/web/staticfiles/:rw
      - media_volume:/home/app/web/media/:rw
 
  ssl-generator:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
  tg_bot:
    image: killka1997/cctelegrambot
    environment:
    - TELEGRAM_TOKEN=5776306301:AAGITlyxjF3tUyE6Md3g5IWDTQaW3qGfy8Q
    - WEB_URL=http://web:8000
    - HOST=0.0.0.0
    - PORT=6666
    depends_on:
    - web


volumes:
  static_volume:
    driver: local
  media_volume:
    driver: local
  postgres_data:
    driver: local