# Generated by Django 2.2.28 on 2022-07-07 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Наименование')),
                ('BIK', models.TextField(max_length=10, verbose_name='БИК')),
            ],
        ),
        migrations.CreateModel(
            name='Bank_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.TextField(max_length=36, verbose_name='ГУИД 1с')),
                ('account_number', models.TextField(max_length=100, verbose_name='Номер счета')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.TextField(max_length=36, verbose_name='ГУИД 1с')),
                ('biin', models.TextField(max_length=12, verbose_name='ИИН')),
                ('name', models.TextField(max_length=150, verbose_name='Наименование')),
                ('KBE', models.TextField(max_length=2, verbose_name='КБЕ')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.TextField(max_length=36, verbose_name='ГУИД 1с')),
                ('name', models.TextField(max_length=200, verbose_name='Наименование')),
                ('number', models.TextField(max_length=20, verbose_name='Номер договора')),
                ('date', models.DateField(verbose_name='Дата договора')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Наименование')),
                ('code', models.TextField(max_length=3, verbose_name='Код валюты')),
            ],
        ),
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок согласования')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Наименование')),
                ('roles', models.ManyToManyField(through='ChainControl.Ordering', to='ChainControl.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_before', models.DateField(verbose_name='Завершить до')),
                ('invoice_number', models.TextField(max_length=20, verbose_name='Номер счета на оплату')),
                ('invoice_date', models.DateField(verbose_name='Дата счета на оплату')),
                ('invoice_details', models.TextField(max_length=200, verbose_name='Содержание')),
                ('AVR_date', models.DateField(verbose_name='Дата оказания услуг/передачи товара')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('comment', models.TextField(max_length=200, verbose_name='Комментарий')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.Bank_account')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.Client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.Contract')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.Payment_type')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.Request_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ordering',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.Request_type'),
        ),
        migrations.AddField(
            model_name='ordering',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.Role'),
        ),
        migrations.AddField(
            model_name='ordering',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bank_account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.Client'),
        ),
        migrations.AddField(
            model_name='bank_account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.Currency'),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Согласована')),
                ('order', models.IntegerField(verbose_name='Порядок согласования')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.Request')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Additional_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Приложение')),
                ('request_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.Request')),
            ],
        ),
    ]
