# Generated by Django 2.2.28 on 2022-07-08 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['complete_before'], 'verbose_name_plural': 'Requests'},
        ),
        migrations.AddField(
            model_name='currency',
            name='code_str',
            field=models.TextField(default=django.utils.timezone.now, max_length=3, verbose_name='Код валюты строкой'),
            preserve_default=False,
        ),
    ]
