# Generated by Django 2.2.28 on 2022-07-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0004_auto_20220709_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Статус заявки'),
        ),
    ]
