# Generated by Django 2.2.28 on 2022-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0005_request_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='KBE',
            field=models.TextField(blank=True, max_length=2, null=True, verbose_name='КБЕ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='biin',
            field=models.TextField(blank=True, max_length=12, null=True, verbose_name='ИИН'),
        ),
    ]
