# Generated by Django 3.2.14 on 2022-08-04 16:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0007_auto_20220713_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('1', 'Создана новая заявка'), ('100', 'Заявка выполнена')], default='1', max_length=3, unique=True, verbose_name='Тип шаблона')),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='approval',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='request',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='approval',
            name='new_status',
            field=models.CharField(choices=[('OP', 'Открыта'), ('OA', 'На согласовании'), ('AP', 'Согласована'), ('OR', 'На доработке'), ('CA', 'Отменена'), ('DO', 'Выполнена')], default='OA', max_length=2, verbose_name='Установленный статус'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('OP', 'Открыта'), ('OA', 'На согласовании'), ('AP', 'Согласована'), ('OR', 'На доработке'), ('CA', 'Отменена'), ('DO', 'Выполнена')], default='OA', max_length=2, verbose_name='Статус заявки'),
        ),
    ]
