# Generated by Django 3.2.14 on 2022-08-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0008_auto_20220804_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='status',
            new_name='request_status',
        ),
    ]
