# Generated by Django 3.2.14 on 2022-08-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0010_rename_request_status_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_templates',
            name='subject',
            field=models.CharField(default=123, max_length=100, verbose_name='Тема письма'),
            preserve_default=False,
        ),
    ]
