# Generated by Django 3.2.14 on 2022-08-06 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0011_email_templates_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата оказания услуг/передачи товара'),
            preserve_default=False,
        ),
    ]
