# Generated by Django 3.2.14 on 2022-08-07 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0012_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 7, 23, 22, 30, 47447), verbose_name='Дата создания'),
        ),
    ]
