# Generated by Django 3.2.14 on 2022-08-07 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0014_alter_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
    ]
