# Generated by Django 3.2.14 on 2022-08-11 08:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0015_alter_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_templates',
            name='notification_subject',
            field=models.CharField(default='123', max_length=100, verbose_name='Заголовок уведомления'),
        ),
        migrations.AddField(
            model_name='email_templates',
            name='notification_text',
            field=models.CharField(default='123', max_length=100, verbose_name='Текст уведомления'),
        ),
        migrations.AlterField(
            model_name='email_templates',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст письма'),
        ),
    ]
