# Generated by Django 3.2.14 on 2022-08-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0016_auto_20220811_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ChainControl.currency', verbose_name='Валюта'),
            preserve_default=False,
        ),
    ]
