# Generated by Django 3.2.14 on 2022-08-12 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChainControl', '0017_request_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('OP', 'Открыта'), ('OA', 'На согласовании'), ('AP', 'Согласована'), ('OR', 'На доработке'), ('CA', 'Отменена'), ('DO', 'Выполнена')], max_length=2, null=True, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарий')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.request')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
