# Generated by Django 3.2.14 on 2022-08-12 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0018_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата события'),
        ),
    ]
