# Generated by Django 3.2.14 on 2022-08-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0022_alter_email_templates_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_templates',
            name='email_type',
            field=models.CharField(choices=[('1', 'Создана новая заявка'), ('10', 'Заявка ожидает согласования'), ('20', 'Заявка на доработке'), ('50', 'Заявка отменена'), ('70', 'Заявка согласована всеми участниками и ожидает исполнения'), ('100', 'Заявка выполнена'), ('200', 'Ежедневное напоминание о необходимости согласования'), ('210', 'Ежедневное напоминание о необходимости исполнения'), ('220', 'Напоминание о просроченных заявках')], default='1', max_length=3, unique=True, verbose_name='Тип шаблона'),
        ),
    ]
