# Generated by Django 3.2.14 on 2022-08-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0023_alter_email_templates_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='guid',
            field=models.TextField(default=123, max_length=36, verbose_name='ГУИД 1с'),
            preserve_default=False,
        ),
    ]
