# Generated by Django 3.2.14 on 2022-08-17 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0026_auto_20220818_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_account',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ChainControl.bank'),
        ),
    ]
