# Generated by Django 3.2.14 on 2022-09-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0027_alter_bank_account_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tg_chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID чата (телеграм)'),
        ),
    ]
