# Generated by Django 3.2.14 on 2022-09-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0028_userprofile_tg_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_templates',
            name='tg_text',
            field=models.CharField(default='123', max_length=100, verbose_name='Текст телеграмм сообщения'),
        ),
    ]
