# Generated by Django 3.2.14 on 2022-09-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0029_email_templates_tg_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_templates',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Текст письма'),
        ),
    ]
