# Generated by Django 3.2.14 on 2022-09-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0030_alter_email_templates_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_templates',
            name='notification_text',
            field=models.TextField(default='123', max_length=400, verbose_name='Текст уведомления'),
        ),
        migrations.AlterField(
            model_name='email_templates',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Текст письма'),
        ),
    ]
