# Generated by Django 3.2.14 on 2022-09-16 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0032_alter_email_templates_tg_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='AVR_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оказания услуг/передачи товара'),
        ),
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='request',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ChainControl.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='request',
            name='invoice_details',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Содержание'),
        ),
    ]
