# Generated by Django 3.2.14 on 2022-09-16 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0033_auto_20220916_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChainControl.currency', verbose_name='Валюта договора'),
        ),
    ]
