# Generated by Django 3.2.14 on 2022-10-04 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChainControl', '0034_contract_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_type',
            name='initiator',
        ),
        migrations.CreateModel(
            name='Initiator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.request_type')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.role')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
