# Generated by Django 3.2.14 on 2022-10-05 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0035_auto_20221004_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_type',
            name='executor',
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.request_type')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.role')),
            ],
        ),
    ]
