# Generated by Django 3.2.14 on 2022-10-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0036_auto_20221005_1501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Executor',
            new_name='RequestExecutor',
        ),
    ]
