# Generated by Django 3.2.14 on 2022-10-12 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0037_rename_executor_requestexecutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.TextField(max_length=36, verbose_name='ГУИД 1с')),
                ('name', models.TextField(max_length=150, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
            },
        ),
        migrations.AlterModelOptions(
            name='additional_file',
            options={'verbose_name': 'Вложение', 'verbose_name_plural': 'Вложения'},
        ),
        migrations.AlterModelOptions(
            name='approval',
            options={'verbose_name': 'Согласование', 'verbose_name_plural': 'Согласования'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Банк', 'verbose_name_plural': 'Банки'},
        ),
        migrations.AlterModelOptions(
            name='bank_account',
            options={'verbose_name': 'Банковский счет', 'verbose_name_plural': 'Банковские счета'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Договор контрагента', 'verbose_name_plural': 'Договоры контрагентов'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AlterModelOptions(
            name='email_templates',
            options={'verbose_name': 'Шаблон уведомлений', 'verbose_name_plural': 'Шаблоны уведомлений'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История изменения', 'verbose_name_plural': 'История изменений'},
        ),
        migrations.AlterModelOptions(
            name='initiator',
            options={'verbose_name': 'Иницатор', 'verbose_name_plural': 'Инициаторы'},
        ),
        migrations.AlterModelOptions(
            name='ordering',
            options={'verbose_name': 'Порядок согласования', 'verbose_name_plural': 'Порядки согласования'},
        ),
        migrations.AlterModelOptions(
            name='payment_type',
            options={'verbose_name': 'Тип оплаты', 'verbose_name_plural': 'Типы оплаты'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['complete_before'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='request_type',
            options={'verbose_name': 'Вид заявки', 'verbose_name_plural': 'Виды заявок'},
        ),
        migrations.AlterModelOptions(
            name='requestexecutor',
            options={'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Доп. информация', 'verbose_name_plural': 'Доп. информации'},
        ),
        migrations.CreateModel(
            name='Individual_bank_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.TextField(max_length=36, verbose_name='ГУИД 1с')),
                ('account_number', models.TextField(max_length=100, verbose_name='Номер счета')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ChainControl.bank')),
                ('individual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ChainControl.individual')),
            ],
            options={
                'verbose_name': 'Карт-счет',
                'verbose_name_plural': 'Карт-счета',
            },
        ),
    ]
