# Generated by Django 3.2.14 on 2022-10-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0038_auto_20221012_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='BIK',
            field=models.CharField(max_length=10, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='guid',
            field=models.CharField(max_length=36, verbose_name='ГУИД 1с'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='bank_account',
            name='account_number',
            field=models.CharField(max_length=100, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='bank_account',
            name='guid',
            field=models.CharField(max_length=36, verbose_name='ГУИД 1с'),
        ),
        migrations.AlterField(
            model_name='client',
            name='KBE',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='КБЕ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='biin',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='guid',
            field=models.CharField(max_length=36, verbose_name='ГУИД 1с'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='guid',
            field=models.CharField(max_length=36, verbose_name='ГУИД 1с'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Код валюты'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code_str',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Код валюты строкой'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='guid',
            field=models.CharField(max_length=36, verbose_name='ГУИД 1с'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='guid',
            field=models.CharField(max_length=36, verbose_name='ГУИД 1с'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='individual_bank_account',
            name='account_number',
            field=models.CharField(max_length=100, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='individual_bank_account',
            name='guid',
            field=models.CharField(max_length=36, verbose_name='ГУИД 1с'),
        ),
        migrations.AlterField(
            model_name='payment_type',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='request',
            name='invoice_details',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='request',
            name='invoice_number',
            field=models.CharField(max_length=20, verbose_name='Номер счета на оплату'),
        ),
        migrations.AlterField(
            model_name='request_type',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование'),
        ),
    ]
