# Generated by Django 3.2.14 on 2022-10-12 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChainControl', '0039_auto_20221012_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_file',
            name='request_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.request', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.request', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChainControl.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='bank_account',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ChainControl.bank', verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='bank_account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.client', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='bank_account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.client', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='history',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.request', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='individual_bank_account',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ChainControl.bank', verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='individual_bank_account',
            name='individual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ChainControl.individual', verbose_name='Физ. лицо'),
        ),
        migrations.AlterField(
            model_name='initiator',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.request_type', verbose_name='Вид заявки'),
        ),
        migrations.AlterField(
            model_name='initiator',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='initiator',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.request_type', verbose_name='Вид заявки'),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='request',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.bank_account', verbose_name='Банковский счет'),
        ),
        migrations.AlterField(
            model_name='request',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.client', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='request',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='request',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.payment_type', verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.request_type', verbose_name='Вид заявки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='request_type',
            name='roles',
            field=models.ManyToManyField(through='ChainControl.Ordering', to='ChainControl.Role', verbose_name='Порядок согласования'),
        ),
        migrations.AlterField(
            model_name='requestexecutor',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.request_type', verbose_name='Вид заявки'),
        ),
        migrations.AlterField(
            model_name='requestexecutor',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainControl.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
