# Generated by Django 3.2.14 on 2022-10-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0040_auto_20221012_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ChainControl.individual', verbose_name='Физ. лицо'),
        ),
        migrations.AddField(
            model_name='request',
            name='individual_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ChainControl.individual_bank_account', verbose_name='Карт-счет'),
        ),
        migrations.AddField(
            model_name='request',
            name='is_accountable_person',
            field=models.BooleanField(default=False, verbose_name='Оплата подотчетному лицу'),
        ),
        migrations.AlterField(
            model_name='request',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ChainControl.bank_account', verbose_name='Банковский счет'),
        ),
        migrations.AlterField(
            model_name='request',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ChainControl.contract', verbose_name='Договор'),
        ),
    ]
