# Generated by Django 3.2.14 on 2022-10-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0041_auto_20221013_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_type',
            name='cashless',
            field=models.BooleanField(default=False, verbose_name='Это безналичный расчет'),
        ),
    ]
