# Generated by Django 3.2.14 on 2022-10-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0042_payment_type_cashless'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='BIK',
            field=models.CharField(max_length=20, verbose_name='БИК'),
        ),
    ]
