# Generated by Django 3.2.14 on 2022-10-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0043_alter_bank_bik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер договора'),
        ),
    ]
