# Generated by Django 3.2.14 on 2022-11-06 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0045_auto_20221101_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='mission',
            name='complete_before',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Завершить до'),
            preserve_default=False,
        ),
    ]
