# Generated by Django 3.2.14 on 2022-11-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ChainControl', '0046_auto_20221106_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='can_edit',
            field=models.BooleanField(default=False, verbose_name='Может доработать заявку'),
        ),
        migrations.AddField(
            model_name='ordering',
            name='can_edit',
            field=models.BooleanField(default=False, verbose_name='Может доработать заявку'),
        ),
        migrations.AlterField(
            model_name='additional_file',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('model', 'request'), ('model', 'mission'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('model', 'request'), ('model', 'mission'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='history',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('model', 'request'), ('model', 'mission'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='initiator',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('model', 'request_type'), ('model', 'mission_type'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('model', 'request_type'), ('model', 'mission_type'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='requestexecutor',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('model', 'request_type'), ('model', 'mission_type'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
