# Generated by Django 3.2.14 on 2022-11-06 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0047_auto_20221106_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='date_from',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date_to',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата окончания'),
        ),
    ]
