# Generated by Django 3.2.14 on 2022-11-06 15:00

from django.db import migrations, models
import django.db.models.deletion

def email_templates_update(apps, schema_editor):
    Email_templates = apps.get_model('ChainControl', 'Email_templates')
    ContentType =  apps.get_model('contenttypes', 'ContentType')
    Request = apps.get_model('ChainControl', 'Request')
    for a in Email_templates.objects.all():
        a.content_type = ContentType.objects.get_for_model(Request)
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ChainControl', '0048_auto_20221106_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_templates',
            name='content_type',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(('model', 'request'), ('model', 'mission'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.RunPython( email_templates_update )
    ]
