# Generated by Django 3.2.14 on 2022-11-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0049_email_templates_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestexecutor',
            name='can_edit',
            field=models.BooleanField(default=False, verbose_name='Может доработать заявку'),
        ),
        migrations.AlterField(
            model_name='email_templates',
            name='email_type',
            field=models.CharField(choices=[('1', 'Создана новая заявка'), ('10', 'Заявка ожидает согласования'), ('20', 'Заявка на доработке'), ('50', 'Заявка отменена'), ('70', 'Заявка согласована всеми участниками и ожидает исполнения'), ('100', 'Заявка выполнена'), ('200', 'Ежедневное напоминание о необходимости согласования'), ('210', 'Ежедневное напоминание о необходимости исполнения'), ('220', 'Напоминание о просроченных заявках')], default='1', max_length=3, verbose_name='Тип шаблона'),
        ),
    ]
