# Generated by Django 3.2.14 on 2022-11-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0050_auto_20221107_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='daily_allowance',
            field=models.FloatField(default=0, verbose_name='Суточные'),
            preserve_default=False,
        ),
    ]
