# Generated by Django 3.2.14 on 2022-11-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0051_mission_daily_allowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='cost_of_living',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость проживания'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='daily_allowance',
            field=models.FloatField(blank=True, null=True, verbose_name='Суточные'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='ticket_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость билетов'),
        ),
    ]
