# Generated by Django 3.2.14 on 2022-11-07 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0052_auto_20221107_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
    ]
