# Generated by Django 3.2.14 on 2022-11-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0053_alter_mission_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['complete_before'], 'verbose_name': 'Заявка на оплату', 'verbose_name_plural': 'Заявки на оплату'},
        ),
    ]
