# Generated by Django 3.2.14 on 2022-11-21 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0055_auto_20221115_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country_of_residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
                ('guid', models.CharField(max_length=36, verbose_name='ГУИД 1с')),
            ],
            options={
                'verbose_name': 'Страна резидентства',
                'verbose_name_plural': 'Страны резидентства',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='is_non_resident',
            field=models.BooleanField(default=False, verbose_name='Нерезидент'),
        ),
        migrations.AddField(
            model_name='client',
            name='country_of_residence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChainControl.country_of_residence', verbose_name='Страна резидентства'),
        ),
    ]
