# Generated by Django 3.2.14 on 2022-11-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0056_auto_20221121_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='invoice_details',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Содержание'),
        ),
    ]
