# Generated by Django 3.2.14 on 2022-12-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainControl', '0057_alter_request_invoice_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Комментарий'),
        ),
    ]
