# Generated by Django 3.2.14 on 2022-08-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwa_webpush', '0002_auto_20220718_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushmessage',
            name='title',
            field=models.CharField(default='Message from ChainControl.', max_length=200),
        ),
    ]
