# Generated by Django 3.2.14 on 2022-09-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwa_webpush', '0003_alter_pushmessage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushmessage',
            name='title',
            field=models.CharField(default='Message from CC.', max_length=200),
        ),
    ]
